name: manifest-checks

# on:
#   pull_request:
#     branches:
#       - master
#     # Commenting out paths for now until GH Actions
#     # Have good suport for required checks + path filters
#     # https://github.community/t5/GitHub-Actions/Feature-request-conditional-required-checks/m-p/36938#M2735
#     #paths:
#     #  - 'deploy/**'
#   push:
#     branches:
#       - master
on:
  push:
    branches:
      - test

  workflow_dispatch:
    inputs:
      tags:
        description: Choose Tag to Run Tests With
        default: smoke
        required: false

# Jobs
jobs:
  # Job to check for manifest changes
  compare-manifests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup KinD Cluster
      timeout-minutes: 10
      uses: engineerd/setup-kind@v0.5.0
      with:
          version: "v0.11.1"
          image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
          wait: 360s

    - name: Check for manifest changes
      timeout-minutes: 5
      run: |
        make ci-bootstrap
        make compare-single-manifest