name: repo-checks

# on:
#   pull_request:
#     branches:
#       - master
#   push:
#     branches:
#       - master
on:
  push:
    branches:
      - test

  workflow_dispatch:
    inputs:
      tags:
        description: Choose Tag to Run Tests With
        default: smoke
        required: false

# Jobs
jobs:
  # Job to lint code
  boilerplate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check boilerplate
      timeout-minutes: 5
      run: |
        make boilerplate